- name: Create a MariaDB container
  community.docker.docker_container:
        name: photoprismDatabase
        image: mariadb:10.11
        restart_policy: unless-stopped
        stop_timeout: 5
        security_opts:
          - seccomp=unconfined
          - apparmor=unconfined
        command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
        volumes:
          - "/home/prajwal/dockerCompose/photoprism/database:/var/lib/mysql"
        env:
          MARIADB_AUTO_UPGRADE: "1"
          MARIADB_INITDB_SKIP_TZINFO: "1"
          MARIADB_DATABASE: "photoprism"
          MARIADB_USER: "photoprism"
          MARIADB_PASSWORD: "insecure"
          MARIADB_ROOT_PASSWORD: "insecure"
        ports:
          - "3306:3306"

- name: wait for database to come up
  ansible.builtin.wait_for:
    port: 3306
    delay: 10

- name: Create a PhotoPrism container
  community.docker.docker_container:
        name: photoprism
        image: photoprism/photoprism:latest
        stop_timeout: 10
        security_opts:
          - seccomp=unconfined
          - apparmor=unconfined
        ports:
          - "2342:2342"
        env:
          PHOTOPRISM_ADMIN_USER: "admin"
          PHOTOPRISM_ADMIN_PASSWORD: "insecure"
          PHOTOPRISM_AUTH_MODE: "password"
          PHOTOPRISM_SITE_URL: "http://192.168.1.11:2342/"
          PHOTOPRISM_DISABLE_TLS: "false"
          PHOTOPRISM_DEFAULT_TLS: "true"
          # Add other environment variables as needed
        volumes:
          - "/media/External HHD/media files/photos:/photoprism/originals"
          - "/media/External HHD/media files/photos:/photoprism/import"
          - "/home/prajwal/dockerCompose/photoprism/storage:/photoprism/storage"

