- name: Create the pihole Docker container
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole
    restart_policy: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    
    volumes:
      - "/home/prajwal/dockerCompose/pihole/etc-pihole:/etc/pihole"
      - "/home/prajwal/dockerCompose/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"

    env:
      TZ: "Asia/Kolkata"
      WEBPASSWORD: "password"
    
    capabilities:
      - NET_ADMIN

    networks:
      - name: dockerNetwork 